name: Feature Request
description: Request a new feature
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        👍 Thanks for helping us improve this project.

  - type: textarea
    id: feature-description
    attributes:
      label: New feature description
      description: Specific use cases or images that describe the feature would be helpful.
    validations:
      required: true

